### ISSUE TITLE
Crashes silently on startup

### ISSUE THREAD

**Issue by Kaede573** [twopointzero/TJAPlayer3#60]
Hello, I have tested TJAPlayer3 on two laptops (Intel CPU and Intel HD GPUs). Both running Windows 10.

On the older laptop, TJAPlayer3 starts with no issue.

On the newer laptop (Kaby Lake CPU), nothing happens, TJAPlayer3 crashes silently.

Setup:
Windows 10 (up to date)
Up to date Intel HD drivers (26.20.100.78.12). Just in case, I have checked they worked properly (started a 3D game, works correctly at normal speed).
.NET Framework 4.8 installed, I think (I have downloaded the installer and it is saying it is already installed, the register keys also seem to indicate I have 4.8).
Switched to Japanese locale. I didn't need to do this on the older PC for it to work, but whatever, since it's recommended, I did that too.
The system hasn't been used much and is pretty close to a clean reinstall after format.

Upon starting TJAPlayer3 nothing happens, no logs, etc. however in Windows Event Viewer I can see this:
```
Application: TJAPlayer3.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at TJAPlayer3.ErrorReporting.ErrorReporter.WithErrorReporting(System.Action)
   at TJAPlayer3.Program.Main()
```

The "Framework Version: v4.0.30319" seems suspicious ?

**Comment by twopointzero** [comment]
Hi there. Thanks for reaching out, and apologies for taking so long to respond to this issue. Things have been nuts these days and focus has sadly had to be placed elsewhere.

The method shown in your (remarkably short!) stack trace does not perform any file access as such, though it does cause the runtime to load some assemblies for code and metadata.

Did this error occur with one of the release packages, or did you build from source? (I ask because the release packages are built such that their stack traces include file information, line numbers, etc.)

Are you using a fresh default config.ini or did you bring one over from another installation somewhere else?

Also, and without disclosing your user name on your machine or any other personal details (though knowing their lengths might help,) can you tell me the full directory where you had TJAPlayer3 installed?

And, one last question for now: Do you use Windows Defender or Malwarebytes or similar software which might accidentally quarantine or outright delete files? (I've not seen this happen with TJAPlayer3 before but figure it worth asking because this stack trace is short and odd.)

Thanks in advance for any information that you are able to provide!

**Comment by yukikiss** [comment]
Hi, i also have same issue that contains **exactly** the same error in event viewer
besides the very short stack trace that appears on event viewer. i also found another error that comes with it every time.

```
Faulting application name: TJAPlayer3.exe, version: 5.2.8.0, time stamp: 0x5f504448
Faulting module name: KERNELBASE.dll, version: 10.0.19041.488, time stamp: 0x42f14898
Exception code: 0xe0434352
Fault offset: 0x00129962
Faulting process id: 0x17f0
Faulting application start time: 0x01d69f9b26d47ffe
Faulting application path: C:\Users\[user name]\Desktop\TJAPlayer3_v5.2.8.Branch.master.Sha.398fc66d02048a9ce1431b352345f637ca895cfa (2)\TJAPlayer3.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 48625cf0-c078-4818-9658-74642e2b5bf1
Faulting package full name: 
Faulting package-relative application ID: 
```
*note: my user name is very short and only contain alphabetic characters 

i am running a 3rd gen Ryzen 3 processor (no built-in graphics) with a NVIDIA GTX9XX GPU in a almost-clean environment (this machines is built very recently)
tested it with another machine with Ryzen 3400G but it work just fine.

Both machine are in Windows 10 ,have .NET framework 4.8, Japanese language pack installed and switched into Japanese locale

this error occurs in the release package (i have tested it in version 5.2.6 to 5.2.8 but result are the same)

i am unable to start the application so seems there are no config.ini for me
but even i move my folder from my another machine (that can run the application without any problem) to my current machines, same issue still happen.

My windows defender is on but it didn't take any actions related to this application.

Thanks!

**Comment by twopointzero** [comment]
@yukikiss That's not even remotely the same error :P but thanks for passing it along. Are you able to run any other versions, or have you been able to run any in the past which you now cannot run?

**Comment by twopointzero** [comment]
@Kaede573 Can you confirm your exact Windows 10 version? (Microsoft have reportedly screwed up some recent ones.) And was/is this machine able to launch any other specific versions of TJAPlayer3?

**Comment by Kaede573** [comment]
Hello twopointzero.
Sorry for taking so long to respond myself.

I'm running the latest release (https://github.com/twopointzero/TJAPlayer3/releases), I've just downloaded the binaries.

Using fresh config.ini.

Installation directory is nothing special, no spaces or non ASCII characters (C:\portableSofts\_games\TJAPlayer3).

I'm using Windows Defender, yes. I've just done the same as yukikiss suggested above (copy installation folder to another machine): it works, the application starts.

The laptop that fails running TJAPlayer3 is running W10 "Version 2004 (OS Build 19041.450).

**Comment by twopointzero** [comment]
Hi @Kaede573 and @yukikiss.

While making some other changes which will be going into 5.2.9, I adjusted the ErrorReporter startup process a bit, updated some packages, and removed some dependencies which are no longer required. The likelihood of addressing your issue is low, but it might be worth giving [this pre-release build](https://ci.appveyor.com/api/buildjobs/2vgtqkpl3ladacrd/artifacts/TJAPlayer3_v5.2.9-reduce-custom-skin-error-reporting.1%2B4.Branch.reduce-custom-skin-error-reporting.Sha.d6bc35f6e6eb115a69be7270851e326955d97889.7z) a try and letting me know if it works or continues to fail for you.

**Comment by Kaede573** [comment]
I get a different error with the new build.
Please note that since I could start the program with default settings / no locale change, I just downloaded and started it as is.

I get different error with this build now (in the event viewer, the application doesn't report anything on startup), it is a bit more verbose. Below is all I found in the event viewer.

Level=Error, Source=.NET Runtime:
```
Application: TJAPlayer3.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at TJAPlayer3.ErrorReporting.ErrorReporter+<>c.<WithErrorReporting>b__5_0(Sentry.SentryOptions)
   at Sentry.SentrySdk.Init(System.Action`1<Sentry.SentryOptions>)
   at TJAPlayer3.ErrorReporting.ErrorReporter.WithErrorReporting(System.Action)
   at TJAPlayer3.Program.Main()
```

Level=Error, Source=Application Error```

Faulting application name: TJAPlayer3.exe, version: 5.2.9.0, time stamp: 0x5f8b5d04
Faulting module name: KERNELBASE.dll, version: 10.0.19041.423, time stamp: 0x09cf3bbe
Exception code: 0xe0434352
Fault offset: 0x00129962
Faulting process id: 0x1acc
Faulting application start time: 0x01d6a54b1df553d4
Faulting application path: C:\portableSofts\_games\TJAPlayer3_v5.2.9-reduce-custom-skin-error-reporting.1+4.Branch.reduce-custom-skin-error-reporting.Sha.d6bc35f6e6eb115a69be7270851e326955d97889\TJAPlayer3.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b52ba366-6fc0-45d7-afbe-1c0edcc4a410
Faulting package full name: 
Faulting package-relative application ID: 
```

Level=Information, Source=Windows Error Reporting:```

Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: TJAPlayer3.exe
P2: 5.2.9.0
P3: 5f8b5d04
P4: Sentry
P5: 2.1.6.0
P6: c2be18b5
P7: 9b
P8: 9
P9: System.IO.FileNotFoundException
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_TJAPlayer3.exe_8f431efea98777cbc4a6e531bd173df50e572ea_a2aa6ad3_a4f032a7-606e-422b-9982-9ef5c314b6f0

Analysis symbol: 
Rechecking for solution: 0
Report Id: b52ba366-6fc0-45d7-afbe-1c0edcc4a410
Report Status: 4
Hashed bucket: 
Cab Guid: 0
```

Level=Information, Source=Windows Error Reporting:
```
Fault bucket 2031833660477648571, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: TJAPlayer3.exe
P2: 5.2.9.0
P3: 5f8b5d04
P4: Sentry
P5: 2.1.6.0
P6: c2be18b5
P7: 9b
P8: 9
P9: System.IO.FileNotFoundException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9E03.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TJAPlayer3.exe_8f431efea98777cbc4a6e531bd173df50e572ea_a2aa6ad3_a4f032a7-606e-422b-9982-9ef5c314b6f0

Analysis symbol: 
Rechecking for solution: 0
Report Id: b52ba366-6fc0-45d7-afbe-1c0edcc4a410
Report Status: 268435456
Hashed bucket: e38c5f447143c3b07c3285f2f773aebb
Cab Guid: 0
```

**Comment by twopointzero** [comment]
@Kaede573 Those are super-awesome details, so thanks very much for them! The stack trace is still both odd and shallow, but it is deeper than the ones before so that actually does help narrow things down a bit.

We're still shooting in the dark a bit, especially since the code indicated by that stack trace doesn't do anything that should be able to produce that particular type of error, so I might need to ask you to try a few things and then we can go from there.

### Checking .NET Version

To double-check exactly which version of .NET you have installed, can you open a Command Prompt as Administrator, run the following command, and reply with the results? (This just reads the registry and returns a bit of information regarding installed .NET 4.x frameworks.)

`reg query "HKLM\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4" /s`

### Checking Windows Version

And to check the exact type and build of Windows, can you run this command and provide those results also?

`systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`

### TJAPlayer3 installation directory (especially length)

You might want to try extracting TJAPlayer3 into a shorter folder name than you have been, just to make sure we are not running into a path length issue. Those usually throw a different error, but it is worth a try.

### TJAPlayer3 test builds, just for you guys. ;)

I also have created three new TJAPlayer3 variations which you can try in sequence and let me know which of them work for you. Please try them extracted to separate folders, rather than overwriting files in one folder, and please try all three even if one of them works right away:

* https://ci.appveyor.com/api/buildjobs/src0wvye9axfvw0n/artifacts/TJAPlayer3_v5.2.9-reduce-custom-skin-error-reporting.1%2B5.Branch.reduce-custom-skin-error-reporting.Sha.737d0c1925adfb91d8995acc675436f97377bfbb.7z
* https://ci.appveyor.com/api/buildjobs/ek1fb0oc0r89xhpi/artifacts/TJAPlayer3_v5.2.9-spike-try-alpha-sentry.1%2B7.Branch.spike-try-alpha-sentry.Sha.7d1befa8fe980503089c34b93474eac3ec875385.7z
* https://ci.appveyor.com/api/buildjobs/vhfve069tb9tu3yu/artifacts/TJAPlayer3_v5.2.9-spike-try-removing-sentry.1%2B8.Branch.spike-try-removing-sentry.Sha.810f3313378bdc3e8341dd007fff0a066a61db9a.7z

As with the earlier suggestion, it would be best to extract these three archives into shorter directory names.

**Comment by Kaede573** [comment]
Hello, sorry it took me so long. Unfortunately none of the 3 test buils start - I have attached the information about .NET framework version and OS build (using given commands), and full application logs after starting the 3 builds in the following order: 7d1be, 737d0, 810f3.

**Comment by twopointzero** [comment]
Hey, @Kaede573, thanks so much for the event log export and registry output, and sorry for not having a chance to reply sooner; things have been nuts.

Thanks for trying all those builds; I know that was probably really annoying to do and the results are unfortunately not pointing anywhere good.

All three tests produce a similar end result but the third one is the most interesting because I completely removed all of the error reporting code (where the other two, and the versions you tried before, were crashing somewhere that already made no sense) and that third test just turned right around and crashed on the very next, very different, thing it tried to do, and with the same odd low-level error.

At this point I have to start assuming you have a pretty low-level problem with your Windows install, or at the very least with your .NET Framework install. If you're up for it, Windows and/or .NET Framework repair attempts are probably the next bet, unfortunately. :/

**Comment by Kaede573** [comment]
Thank you very much for all the tests build and troubleshooting guidance twopointzero, it was much appreciated.

I don't use that system often, but I'll try a .NET Framework repair, yes, and after that a full OS reinstall (since I don't have much data / many programs on that machine), see if I can replicate the issue after that.

Since nobody ever reported this issue, I also think it's safe to assume it is an issue on my end, sorry for the trouble.
I'll try to remember to post an update next time I give this a try, and am closing this issue since I don't want to clutter the issue tracker.
