### ISSUE TITLE
About Android version

### ISSUE THREAD

**Issue by Electr0Whale** [twopointzero/TJAPlayer3#74]
Do you have any plans to develop an Android version? Not just me, there are many people who want to play TJAPlayer3 on their mobile phones.

**Comment by twopointzero** [comment]
It has honestly been a while since I've been involved in the taiko simulator community (oh, for lack of hours in the day!) but as I recall there has long been a taiko simulator for Android which may trace some of its lineage back to earlier TJAPlayer forks, though there is no association that I'm aware of with TJAPlayer3. You should be able to find it out there, though as someone on iOS and not Android I cannot suggest much as to where to find it, how to install it, etc.

This particular taiko simulator codebase is not heading toward Android. It is barely maintainable even for modern Windows given the amount of mess created by various maintainers and contributors over the years.
