### ISSUE TITLE
Is there compatibility with TJAStudio

### ISSUE THREAD

**Issue by nkmkormu** [twopointzero/TJAPlayer3#75]
The execute function in TJAStudio chart editor shows you can launch TJAPlayer with the song currently being edited
and have that song autoupdate for changes when you press f5 without closing the window.
However this feature doesn't work for some reason, it will just launch the player and not open the song.

**Comment by twopointzero** [comment]
Support for TJAStudio (external control and plugin support, more accurately) was removed due to lack of use and maintainability issues it was causing in the TJAPlayer3 codebase. It had to go in order to make progress on cleaning other things up.

(DirectSound support, as another example, is high on the list of things to remove, and for similar reasons, to be replaced with explicit shared wasapi support (which is what DirectSound actually runs on these days anyway.) Maintainability was sacrificed for so long during TJAPlayer's evolution that things like this are going to have to go from time to time otherwise there will be a day where TJAPlayer3 simply stops working and cannot be resurrected with reasonable effort.)
