### ISSUE TITLE
when moving the tjaplayer3 window from first screen to the second one it crashes.

### ISSUE THREAD

**Issue by elfrichi** [twopointzero/TJAPlayer3#79]
as the title says, can't use it on second screen in a multi screen environment.

**Comment by twopointzero** [comment]
I'm afraid this is a long-standing issue with TJAPlayer (both 3 and earlier/later forks) which won't be addressed without someone wanting to take on a significant overhaul of its graphics subsystem. There is a partial workaround which might work for you, however:

If you open the Config.ini file you can manually set the window location, width, and height in order to place TJAPlayer3 onto the screen you prefer.
